name: Mirror to GitLab & Codeberg

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 0'

jobs:
  mirror:
    uses: spivanatalie64/.github/.github/workflows/mirror.yml@main
    with:
      repo-name: "machbb"
    secrets:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
