(define-module (machbb config)
  #:export (init find-mozconfig write-default-mozconfig mozconfig-env))

(use-modules (ice-9 format) (srfi srfi-1)
             (machbb util))

(define (init . dirs)
  (let ((target (if (pair? dirs) (car dirs) ".")))
    (format #t " ~a Initializing ~a~%" (cyan "⊶") target)
    (let ((mozconfig (string-append target "/mozconfig")))
      (unless (file-exists? mozconfig)
        (write-default-mozconfig mozconfig "acreedom")
        (ok (format #f "Created ~a" mozconfig)))
      (let ((patches (string-append target "/patches")))
        (unless (file-exists? patches)
          (mkdir patches)
          (ok (format #f "Created ~a/" patches)))))
    (ok "Project initialized")))

(define (find-mozconfig)
  (let ((root (project-root)))
    (if root
        (let ((candidates '("mozconfig" "mozconfig.acreedom")))
          (find (lambda (f) (file-exists? (string-append root "/" f))) candidates))
        #f)))

(define (write-default-mozconfig path name)
  (with-output-to-file path
    (lambda ()
      (format #t "# machbb — ~a build configuration~%" name)
      (format #t "# Auto-generated by machbb init~%")
      (format #t "~%")
      (format #t "mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-~a~%" name)
      (format #t "ac_add_options --enable-application=browser~%")
      (format #t "ac_add_options --enable-optimize~%")
      (format #t "ac_add_options --enable-release~%")
      (format #t "ac_add_options --enable-hardening~%")
      (format #t "ac_add_options --disable-telemetry~%")
      (format #t "ac_add_options --disable-crashreporter~%")
      (format #t "ac_add_options --disable-updater~%")))
  (chmod path #o644))

(define* (mozconfig-env #:optional (path #f))
  (let ((mozconfig (or path (find-mozconfig))))
    (if mozconfig
        (begin
          (setenv "MOZCONFIG" (if (string-prefix? "/" mozconfig)
                                  mozconfig
                                  (string-append (getcwd) "/" mozconfig)))
          mozconfig)
        #f)))
